In [15]:
import pandas as pd

# ----------------------------
# 1. Load data
# ----------------------------
df = pd.read_excel("Population_by_area.xlsx")

# Clean column name
df = df.rename(columns={"Unnamed: 0": "Municipality"})

# ----------------------------
# 2. Reshape to long format
# ----------------------------
df_long = df.melt(
    id_vars=["Municipality"],
    var_name="year_quarter",
    value_name="population"
)

# Extract year
df_long["year"] = df_long["year_quarter"].str.extract(r"(\d{4})").astype(int)

# Keep only 2008–2024
df_long = df_long[(df_long["year"] >= 2008) & (df_long["year"] <= 2024)]

# Ensure numeric
df_long["population"] = pd.to_numeric(df_long["population"], errors="coerce")

# ----------------------------
# 3. Aggregate to yearly average
# ----------------------------
df_yearly = (
    df_long
    .groupby(["Municipality", "year"], as_index=False)["population"]
    .mean()
)

# ----------------------------
# 4. Region mapping
# ----------------------------
region_to_municipalities = {
    "Capital Region": [
        "Copenhagen", "Frederiksberg", "Gentofte", "Gladsaxe", "Helsingør",
        "Hillerød", "Hvidovre", "Lyngby-Taarbæk", "Rødovre", "Ballerup",
        "Brøndby", "Dragør", "Egedal", "Fredensborg", "Frederikssund",
        "Furesø", "Gribskov", "Halsnæs", "Herlev", "Høje-Taastrup",
        "Hørsholm", "Ishøj", "Rudersdal", "Tårnby", "Vallensbæk",
        "Albertslund", "Allerød", "Glostrup", "Bornholm"
    ],
    "Zealand Region": [
        "Roskilde", "Holbæk", "Næstved", "Slagelse", "Køge",
        "Guldborgsund", "Vordingborg", "Kalundborg", "Ringsted",
        "Sorø", "Lejre", "Stevns", "Solrød", "Faxe", "Odsherred",
        "Greve", "Lolland"
    ],
    "Central Jutland": [
        "Aarhus", "Randers", "Viborg", "Silkeborg", "Herning",
        "Horsens", "Skanderborg", "Holstebro", "Skive",
        "Ringkøbing-Skjern", "Favrskov", "Hedensted",
        "Syddjurs", "Ikast-Brande", "Norddjurs", "Struer",
        "Odder", "Lemvig", "Samsø"
    ],
    "North Jutland": [
        "Aalborg", "Hjørring", "Frederikshavn", "Thisted",
        "Mariagerfjord", "Jammerbugt", "Vesthimmerland",
        "Brønderslev", "Rebild", "Morsø", "Læsø"
    ],
    "Southern Denmark": [
        "Odense", "Esbjerg", "Vejle", "Kolding", "Sønderborg",
        "Aabenraa", "Svendborg", "Haderslev", "Faaborg-Midtfyn",
        "Varde", "Fredericia", "Vejen", "Assens", "Tønder",
        "Middelfart", "Nyborg", "Nordfyns", "Billund",
        "Kerteminde", "Langeland", "Ærø", "Fanø"
    ]
}

# Convert to lookup dict
municipality_to_region = {
    muni: region
    for region, municipalities in region_to_municipalities.items()
    for muni in municipalities
}

# Map region
df_yearly["Region"] = df_yearly["Municipality"].map(municipality_to_region)
df_yearly

     Municipality  year  population            Region
0        Aabenraa  2008    60316.75  Southern Denmark
1        Aabenraa  2009    60237.00  Southern Denmark
2        Aabenraa  2010    59946.00  Southern Denmark
3        Aabenraa  2011    59750.00  Southern Denmark
4        Aabenraa  2012    59457.25  Southern Denmark
...           ...   ...         ...               ...
1780          Ærø  2020     5970.00  Southern Denmark
1781          Ærø  2021     5998.00  Southern Denmark
1782          Ærø  2022     6039.25  Southern Denmark
1783          Ærø  2023     6003.75  Southern Denmark
1784          Ærø  2024     5937.50  Southern Denmark

[1785 rows x 4 columns]

In [16]:
# 7. Save to CSV
df_yearly.to_csv("population_munc.csv", index=False)

In [17]:
df_yearly = df_yearly.drop(columns=["Municipality"])
df_yearly

      year  population            Region
0     2008    60316.75  Southern Denmark
1     2009    60237.00  Southern Denmark
2     2010    59946.00  Southern Denmark
3     2011    59750.00  Southern Denmark
4     2012    59457.25  Southern Denmark
...    ...         ...               ...
1780  2020     5970.00  Southern Denmark
1781  2021     5998.00  Southern Denmark
1782  2022     6039.25  Southern Denmark
1783  2023     6003.75  Southern Denmark
1784  2024     5937.50  Southern Denmark

[1785 rows x 3 columns]

In [18]:
df_yearly.to_csv("population_reg.csv", index=False)